webtalk_init -webtalk_dir C:/Users/nacho/Documents/Facultad/5to/arqui/tpfinal_mips/mips_final.sim/sim_1/behav/xsim/xsim.dir/io_file_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  2 20:09:01 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3fc1935c-8c29-463f-953c-448196a44fd9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cbbbf05b556d46ac8dc42fad21debae6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "2" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "64 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "2 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "18" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "58080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2177585790 -regid "" -xml C:/Users/nacho/Documents/Facultad/5to/arqui/tpfinal_mips/mips_final.sim/sim_1/behav/xsim/xsim.dir/io_file_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/nacho/Documents/Facultad/5to/arqui/tpfinal_mips/mips_final.sim/sim_1/behav/xsim/xsim.dir/io_file_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/nacho/Documents/Facultad/5to/arqui/tpfinal_mips/mips_final.sim/sim_1/behav/xsim/xsim.dir/io_file_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
